// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS2_KWEUne7JKzP0lz1aPdtiRzMb-hWMc',
    appId: '1:678467051155:web:c1e29b7b5dfa7088acf766',
    messagingSenderId: '678467051155',
    projectId: 'task-management-app-18cbf',
    authDomain: 'task-management-app-18cbf.firebaseapp.com',
    storageBucket: 'task-management-app-18cbf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZp04c6N7c4x2CBPQZ5vu1VjQkfY5gkww',
    appId: '1:678467051155:android:47d67d4f77dcaf0bacf766',
    messagingSenderId: '678467051155',
    projectId: 'task-management-app-18cbf',
    storageBucket: 'task-management-app-18cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFqP2fzLkhHpFJnG_NW8BsGT4olacjPM8',
    appId: '1:678467051155:ios:d665db93afd9a102acf766',
    messagingSenderId: '678467051155',
    projectId: 'task-management-app-18cbf',
    storageBucket: 'task-management-app-18cbf.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
